openapi: '3.0.2'
info:
  title: Sample API
  version: '0.1'
paths:
  /health:
    get:
      operationId: Health
      description: Get health check
      responses:
        '200':
          description: Health check
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /dog/{name}:
    get:
      operationId: GetDog
      description: Get dog by name
      parameters:
        - in: path
          name: name
          required: true
        - in: query
          name: age
          required: false

      responses:
        '200':
          description: Dog data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DogResponse'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string

    DogResponse:
      type: object
      required:
        - age
        - weight
      properties:
        age:
          type: integer
        weight:
          type: integer