openapi: '3.0.2'
info:
  title: Sample API
  version: '0.1'
paths:
  /public/health:
    get:
      operationId: Health
      description: Get health check
      responses:
        '200':
          description: Health check
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
