openapi: '3.0.3'
info:
  title: Sample API
  version: '0.1'
paths:
  /health:
    get:
      operationId: Health
      description: Get health check
      responses:
        '200':
          description: Health check
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /dog/{name}:
    get:
      operationId: GetDog
      description: Get dog by name
      parameters:
      - in: path
        name: name
        required: true
        schema:
          type: string
      - in: query
        name: age
        required: false
        schema:
          type: integer

      responses:
        '200':
          description: Dog data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dogResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      operationId: NewDog
      description: Insert new dog to the db
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewDogRequest'

      responses:
        '200':
          description: New dog inserted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dogResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /dogs:
    get:
      operationId: GetDogs
      description: Get all dogs

      responses:
        '200':
          description: Dogs list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DogsResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: integer

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        result:
          type: boolean

    dogResponse:
      type: object
      required:
        - age
      properties:
        age:
          type: integer
        weight:
          type: number
          format: float

    DogsResponse:
      type: array
      items:
        $ref: '#/components/schemas/dogResponse'

    NewDogRequest:
      type: object
      required:
        - age
      properties:
        age:
          type: integer
        weight:
          type: number
          format: float
